Fix merge commit for "Arm Mbed Online Compiler"
The declarations with "__attribute__ ((alias))" of the malloc related
functions, causes compiler error 308:
  Error: More than one instance of overloaded function "..."  matches
  the argument list in...

Revert the missing __end__ symbol fix from commit id b52815f.