Better malloc overload declarations
Revert the 'extern "C"' from commit 298ff69, but add a 'std::' prefix
in malloc related overloads. Both are intended to fix the error:
  Error: More than one instance of overloaded function...